### PR TITLE
adds timeout to socket event on client side

### PR DESCRIPTION
**Pull request by emilyb7**
builds on #256 

if the browser doesn't get a response from the socket within 20 seconds of emitting a 'goal' event, the update is cancelled and 'pendingSync' is set to false.

related #152

### CODE REVIEW

**Comment by emilyb7** [comment]
potential problem: what if the network's just really slow and it takes more than 20 seconds to get a response from the socket? then everything would get out of sync... not sure how to solve this though...

**Comment by MHemsley** [comment]
I haven’t quite got my head around what’s going on with the Goals app, as I’ve been on leave/not paying as much attention as I would like, but if it’s helpful to talk about the logic/behaviour side of things, please remember that I’m a resource for you to pull on

**Comment by des-des** [comment]
@MHemsley I think this timeout is okay, 20 seconds is a long time for a very small piece of data, so I think it is enough. Mostly, this timeout will only come into play if there is an error on the server and a fails to respond. In this case, the client will retry

**Comment by MHemsley** [comment]
@des-des Agreed, we'll soon find out if there are issues. Is there a limit to the retries?

**Comment by des-des** [comment]
for reference: https://github.com/socketio/socket.io-client-java/issues/309

**Comment by des-des** [comment]
@MHemsley I think for MVP this is robust enough.

There are more complex ways of handling this sort of problem. For example if our number of users was in the tens of thousands, this kind of retry behaviour might overload a server...

If we have a couple of user connected at any one time, even if both of them are retrying every 20s 24 hours a day, this is not problem..

**Pull request merged**
